# Generated by Django 4.0.5 on 2022-06-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlkeywords',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
