# Generated by Django 4.0.5 on 2022-06-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_keywords_urlkeywords_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='UrlKeywords',
        ),
        migrations.AddField(
            model_name='keywords',
            name='url_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scraper.urls'),
        ),
    ]
