# Generated by Django 4.0.5 on 2022-06-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_rename_url_id_keywords_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='urls',
            new_name='url',
        ),
    ]
