# Generated by Django 4.0.5 on 2022-06-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_rename_urls_urls_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
